version: '3.8'
services:

  fuse-server-immunespace:
    build:
      context: .
    ports:
      - $API_PORT:8080
    depends_on:
      - tx-immunespace-groups
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  tx-immunespace-groups:
    image: txscience/tx-immunespace-groups:0.2
    environment:
      APIKEY: $APIKEY


