version: '3.8'
services:

  fuse-server-immunespace:
    build:
      context: .
    ports:
      - $API_PORT:8080
    environment:
      APIKEY: $APIKEY
      USERNAME: $USERNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

